### ISSUE TITLE
Testing v 1.7.1 release candidate

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#279]
Build : https://cbs.centos.org/koji/taskinfo?taskID=81059

Steps to download the Vagrant boxes:
- Libvirt provider: `http://cbs.centos.org/kojifiles/work/tasks/1060/81060/centos-7-adb-1.7-1.x86_64.rhevm.ova`
- Virtualbox provider: `http://cbs.centos.org/kojifiles/work/tasks/1060/81060/centos-7-adb-1.7-1.x86_64.vsphere.ova`

**We should test the following**
- The [Vagrantfiles](https://github.com/projectatomic/adb-atomic-developer-bundle/tree/master/components/centos) and [SCCLI](https://github.com/projectatomic/adb-utils)  work fine with this build

ChangeLog:

```
* Adding openshift2nulecule to ADB @LalatenduMohanty
* Update docs for Fedora libvirt @bexelbie
* Fixing minor typos @Preeticp
* Fixing a typo @Preeticp
* Adding vagrant-service-manager to the Vagrantfiles @LalatenduMohanty
* Removing the sed commands beacsue these are not required anymore @LalatenduMohanty
* Deleting unneeded landrush information @bexelbie
*  Adding changelog for ADB 1.7.0 @@LalatenduMohanty
```

Old Build:  https://cbs.centos.org/koji/taskinfo?taskID=80990

**Comment by brgnepal** [comment]
@LalatenduMohanty  any description?

**Comment by LalatenduMohanty** [comment]
@budhrg 

> any description?

I have updated the description. I was waiting for the build to finish.

**Comment by surajssd** [comment]
I tried this box here are some issues related to `sccli`

``` bash
[hummer@dhcp35-17 adb1.8-test] $ vagrant box add adb1.8 ./centos-7-adb-1.8-0.x86_64.rhevm.ova
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'adb1.8' (v0) for provider: 
    box: Unpacking necessary files from: file:///home/hummer/atomic/adb1.8-test/centos-7-adb-1.8-0.x86_64.rhevm.ova
==> box: Successfully added box 'adb1.8' (v0) for 'libvirt'!
[hummer@dhcp35-17 adb1.8-test] $ vagrant init adb1.8
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
[hummer@dhcp35-17 adb1.8-test] $ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Uploading base box image as volume into libvirt storage...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              adb18-test_default
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              1
==> default:  -- Memory:            512M
==> default:  -- Management MAC:    
==> default:  -- Loader:            
==> default:  -- Base box:          adb1.8
==> default:  -- Storage pool:      default
==> default:  -- Image:             /var/lib/libvirt/images/adb18-test_default.img (41G)
==> default:  -- Volume Cache:      default
==> default:  -- Kernel:            
==> default:  -- Initrd:            
==> default:  -- Graphics Type:     vnc
==> default:  -- Graphics Port:     5900
==> default:  -- Graphics IP:       127.0.0.1
==> default:  -- Graphics Password: Not defined
==> default:  -- Video Type:        cirrus
==> default:  -- Video VRAM:        9216
==> default:  -- Keymap:            en-us
==> default:  -- INPUT:             type=mouse, bus=ps2
==> default:  -- Command line : 
==> default: Creating shared folders metadata...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if its present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Configuring and enabling network interfaces...
==> default: Rsyncing folder: /home/hummer/atomic/adb1.8-test/ => /vagrant

[hummer@dhcp35-17 adb1.8-test] $ vagrant ssh

[vagrant@centos7-adb ~]$ sccli k8s
Generating RSA private key, 2048 bit long modulus
.............................+++
.................................................................................................................................................................+++
e is 65537 (0x10001)
Created symlink from /etc/systemd/system/multi-user.target.wants/etcd.service to /usr/lib/systemd/system/etcd.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/kube-apiserver.service to /etc/systemd/system/kube-apiserver.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/kube-controller-manager.service to /usr/lib/systemd/system/kube-controller-manager.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/kube-scheduler.service to /usr/lib/systemd/system/kube-scheduler.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/kube-proxy.service to /usr/lib/systemd/system/kube-proxy.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/kubelet.service to /usr/lib/systemd/system/kubelet.service.

[vagrant@centos7-adb ~]$ sudo atomic run projectatomic/apache-centos7-atomicapp
Using default tag: latest
Trying to pull repository docker.io/projectatomic/apache-centos7-atomicapp ... latest: Pulling from projectatomic/apache-centos7-atomicapp

47d44cb6f252: Pull complete 
[SNIP]
ca0cdce0d7c7: Pull complete 
Digest: sha256:f7dc30075ebe2047e16b4bd206b186ff45c238eaa58012ff094d16a200c61bc0
Status: Downloaded newer image for docker.io/projectatomic/apache-centos7-atomicapp:latest

Traceback (most recent call last):
  File "/bin/atomic", line 420, in <module>
    sys.exit(args.func())
  File "/usr/lib/python2.7/site-packages/Atomic/atomic.py", line 409, in run
    args = self._get_args("RUN")
  File "/usr/lib/python2.7/site-packages/Atomic/atomic.py", line 351, in _get_args
    labels = self._get_labels()
  File "/usr/lib/python2.7/site-packages/Atomic/atomic.py", line 269, in _get_labels
    return self._getconfig("Labels", [])
  File "/usr/lib/python2.7/site-packages/Atomic/atomic.py", line 256, in _getconfig
    assert self.inspect is not None
AssertionError
[vagrant@centos7-adb ~]$ 
```

Here is paste for these tries: [trial1](http://paste.fedoraproject.org/335778/57452518/) [trial2](http://paste.fedoraproject.org/335781/74527411/)

**Comment by LalatenduMohanty** [comment]
@surajssd The issue is with python-docker-py . refer https://bugzilla.redhat.com/show_bug.cgi?id=1314541
As discussed with  @kadel we are planning to remove it from ADB at this moment. I will send a PR to revert its inclusion. 
That means we do not any new functionality in this release and this is a bug fix release. So the Version has to change to 1.7.1.
@praveenkumar @navidshaikh @bexelbie comments?

**Comment by LalatenduMohanty** [comment]
Here is the PR to remove openshift2nulecule from ADB https://github.com/projectatomic/adb-atomic-developer-bundle/pull/280

**Comment by LalatenduMohanty** [comment]
@surajssd can you also retry downgrading the  package `sudo yum downgrade python-docker-py`?

We cant completely remove python-docker-py as atomic CLI is depended on it.

**Comment by surajssd** [comment]
@LalatenduMohanty simply downgrading `python-docker-py` was not working because it created dependecy conflict, so removed `openshift2nulecule` and then downgraded it, now works like before.

[Paste](http://paste.fedoraproject.org/336008/74871571/) for it.

**Comment by praveenkumar** [comment]
> @praveenkumar @navidshaikh @bexelbie comments?

Make sense to revert back ks changes if O2N is not working as expected and keep bug fix release as 1.7.1 , also please update the title to "Testing v 1.7.1 release candidate" after you have bits in place.

**Comment by LalatenduMohanty** [comment]
@praveenkumar The issue is, even if I remove O2N from ks file , python-docker-py 1.7.0 is available in http://mirror.centos.org/centos-7/7/atomic/x86_64/adb/ and installing atomic CLI will pull it as it a higher version. So the has two steps
- Remove O2N from ks file
- remove python-docker-py from http://mirror.centos.org/centos-7/7/atomic/x86_64/adb/
  Then do a rebuild of the box. I will talk to @kbsingh how we can do that i.e. remove python-docker-py from http://mirror.centos.org/centos-7/7/atomic/x86_64/adb/

**Comment by LalatenduMohanty** [comment]
Looks like we can not take out the python-docker-py 1.7.0 from mirror.c.o. So we have to use `yum downgrade python-docker-py -y` in the ksfile as a workaround.

**Comment by LalatenduMohanty** [comment]
The above issue is fixed in https://cbs.centos.org/koji/taskinfo?taskID=81059

**Comment by LalatenduMohanty** [comment]
Tested `atomic run projectatomic/adb` with `sccli k8s` and it worked fine

**Comment by praveenkumar** [comment]
@LalatenduMohanty when do we plan to release this, or we still have some testing left around it?

**Comment by LalatenduMohanty** [comment]
@praveenkumar yes,  we should do some testing around OpenShift. I am planning to release this today.

**Comment by LalatenduMohanty** [comment]
Actually my Vagrant setup is kind of broken, I am trying to fix it.

**Comment by dharmit** [comment]
Mesos-Marathon Vagrantfile works well. Docker, Mesos & marathon Services up and running.

**Comment by praveenkumar** [comment]
Openshift services are running as expected.
