### ISSUE TITLE
First 'vagrant up' does not complete successfully 

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-atomic-developer-bundle#337]
When creating a new VM via `vagrant up` using [this](http://cdk-builds.usersys.redhat.com/builds/weekly/08-Apr-2016.1/) CDK build and the default _Vagrantfile_, the provisioning does not complete successfully. It ends with "creating symlink":

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'cdk_v2'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: cdk-v2_default_1460124599949_57827
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Registering box with vagrant-registration...
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default: 
    default: This is not an error message; everything may continue to work     properly,
    default: in which case you may ignore this message.
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: Configuring and enabling network interfaces...
==> default: Copying TLS certificates to /Users/hardy/work/developer-platform/    openshift-vagrant/cdk-v2/.vagrant/machines/default/virtualbox/docker
==> default: Created symlink from /etc/systemd/system/multi-user.target.wants/    openshift.service to /usr/lib/systemd/system/openshift.service.    
```

The output how to connect to OpenShift never appears. Most likely some provisioning steps (inside vagrant-service-manager maybe!?) return a non 0 exit code.

**Comment by hferentschik** [comment]
For the record, OpenShift itself is actually running. So the startup seems to succeed after all, but something returns most likely an error code!?

**Comment by hferentschik** [comment]
Running a 'vagrant halt' followed by 'vagrant up' the connection info gets successfully printed. My guess is that vagrant-service-manager already sees that openshift service is enabled and does not do anything.

**Comment by optak** [comment]
For me, `vagrant up` (almost) always finish with return code 126 ("Command invoked cannot execute").
This is bottom of output from `vagrnt up --debug`:

```
DEBUG ssh: stdout: 983aa720a8e7: Download complete
Status: Image is up to date for registry.access.redhat.com/openshift3/ose-sti-builder:v3.1.1.6
registry.access.redhat.com/openshift3/ose-sti-builder: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.


DEBUG ssh: stderr: Created symlink from /etc/systemd/system/multi-user.target.wants/openshift.service to /usr/lib/systemd/system/openshift.service.

 INFO interface: error: Created symlink from /etc/systemd/system/multi-user.target.wants/openshift.service to /usr/lib/systemd/system/openshift.service.

 INFO interface: error: ==> default: Created symlink from /etc/systemd/system/multi-user.target.wants/openshift.service to /usr/lib/systemd/system/openshift.service.
==> default: Created symlink from /etc/systemd/system/multi-user.target.wants/openshift.service to /usr/lib/systemd/system/openshift.service.
 INFO environment: Released process lock: fpcollision
 INFO environment: Released process lock: machine-action-814fef394dcea9557fb9d0f9200fd6ff
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x1dd57f0>

cdk@DESKTOP-NPJE10U ~/cdk/components/rhel/rhel-ose_2
$ echo $?
126
```

**Comment by hferentschik** [comment]
Relates to https://github.com/projectatomic/adb-atomic-developer-bundle/issues/338 which should also be addressed at the same time

**Comment by LalatenduMohanty** [comment]
Looks like lib/vagrant-service-manager/services/open_shift.rb needs to print the stdout . But this does not fix the issue at this moment.

``` r
module Vagrant
  module ServiceManager
    class OpenShift
      def initialize(machine, ui)
        @machine = machine
        @ui = ui
        @extra_cmd = build_extra_command
      end

      def execute
        full_cmd = "#{@extra_cmd} sccli openshift"

        @machine.communicate.sudo(full_cmd) do |type, data|
          if type == :stderr
            @ui.error(data)
            exit 126
          end
        end
      end

      private

      def build_extra_command
        cmd = ''
        CONFIG_KEYS.select {|e| e[/^openshift_/] }.each do |key|
          unless @machine.config.servicemanager.send(key).nil?
            env_name = key.to_s.gsub(/openshift_/,'').upcase
            cmd += "#{env_name}='#{@machine.config.servicemanager.send(key)}' "
          end
        end
        cmd.chop
      end
    end
  end
end
```

**Comment by LalatenduMohanty** [comment]
Filed https://github.com/projectatomic/vagrant-service-manager/issues/163

**Comment by hferentschik** [comment]
> Looks like lib/vagrant-service-manager/services/open_shift.rb needs to print the stdout 

Why? How would that solve the problem? There must be more going on. Say the user adds some custom modifications to the end of the _Vagrantfile_, how would that then work?

**Comment by praveenkumar** [comment]
> Why? How would that solve the problem? There must be more going on. Say the user adds some custom modifications to the end of the Vagrantfile, how would that then work?

I just checked the patch and yes it doesn't solve the issue. What vsm actually doing is using 'sccli' to start the service and then putting that output to console. Now I think we have 2 different solution 
1. Don't use `sccli` for CDK (in vsm) and use a way to figure out box type by parsing `/etc/os-release` 
2. Improve `sccli` script then build cdk-utils and then new vagrant boxes for CDK.

**Comment by hferentschik** [comment]
_vsm_ - vagrant-service-manager!? If `sccli` is the problem (as I suspect as well), the solution is option 2

> What vsm actually doing is using 'sccli' to start the service and then putting that output to console

What's wrong with that? I guess it might depends how it does it. It needs to use the Vagrant logging mechanisms for that. I guess the interesting part is what the vagrant-service-manager code then returns, right?

**Comment by praveenkumar** [comment]
> vsm - vagrant-service-manager!? If sccli is the problem (as I suspect as well), the solution is option 2

Yes, Agree but currrently `sccli` is not mature enough to handle all situation and since our GA is not too far so I will prefer 2nd option. I had talk with @navidshaikh  about same and able to convinced him to send a PR to use `systemctl` for service start/stop/restart instead of `sccli` for CDK box.

> I guess the interesting part is what the vagrant-service-manager code then returns, right? 

Yes, that might be reason ( @navidshaikh might confirm )

**Comment by LalatenduMohanty** [comment]
The question is why sccli is causing the issue? or is it something to do with `machine.communicate.sudo` in VSM? 

``` r
def execute                                 
        full_cmd = "#{@extra_cmd} sccli openshift" 
       @machine.communicate.sudo(full_cmd) do |type, data|                               
```

**Comment by brgnepal** [comment]
@LalatenduMohanty No I doubt. Other wise [this case would have failed.](https://github.com/projectatomic/adb-atomic-developer-bundle/issues/337#issuecomment-207455076)
   $ vagrant halt
   $ vagrant up    # this shows the expected openshift info

**Comment by hferentschik** [comment]
Did anyone test sccli in isolation? What does or return (especially on the very first call)?  Next, what is the return value of the Ruby code calling sccli? Basically we'd like to decompose this problem to find its cause.

**Comment by hferentschik** [comment]
> I had talk with @navidshaikh  about same and able to convinced him to send a PR to use `systemctl` for service start/stop/restart instead of `sccli` for CDK box

Will that offer the same functionality? If so, what is the benefit of sccli in the first place?

**Comment by praveenkumar** [comment]
> Did anyone test sccli in isolation? What does or return (especially on the very first call)? Next, what is the return value of the Ruby code calling sccli?

Yes we did test sccli in isolation and it return `0` after success execution. Now we found `systemctl enable openshift` writes to stderr about linking the unit file but this is not an error, and the exit code is 0.  VSM sees something on stderr, assumes an error has occurred and exits with error code 126. (currently VSM only checking stderr, if there is something then we are blindly exitiing)

We already have a patch for it now from @budhrg https://github.com/projectatomic/vagrant-service-manager/pull/167

**Comment by LalatenduMohanty** [comment]
@hferentschik  @optak  This Vagrantfile can be used as a workaround till we merge the patch in VSM.

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# The private network IP of the VM. You will use this IP to connect to OpenShift.
PUBLIC_ADDRESS="10.1.2.2"

# Number of virtualized CPUs
VM_CPU = ENV['VM_CPU'] || 2

# Amount of available RAM
VM_MEMORY = ENV['VM_MEMORY'] || 3072

# Validate required plugins
REQUIRED_PLUGINS = %w(vagrant-service-manager vagrant-registration)
errors = []

def message(name)
  "#{name} plugin is not installed, run `vagrant plugin install #{name}` to install it."
end
# Validate and collect error message if plugin is not installed
REQUIRED_PLUGINS.each { |plugin| errors << message(plugin) unless Vagrant.has_plugin?(plugin) }
unless errors.empty?
  msg = errors.size > 1 ? "Errors: \n* #{errors.join("\n* ")}" : "Error: #{errors.first}"
  fail Vagrant::Errors::VagrantError.new, msg
end

Vagrant.configure(2) do |config|
  config.vm.box = "cdkv2-rc1"

  config.vm.provider "virtualbox" do |v, override|
    v.memory = VM_MEMORY
    v.cpus   = VM_CPU
    v.customize ["modifyvm", :id, "--ioapic", "on"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.provider "libvirt" do |v, override|
    v.memory = VM_MEMORY
    v.cpus   = VM_CPU
    v.driver = "kvm"
  end

  config.vm.network "private_network", ip: "#{PUBLIC_ADDRESS}"

  if ENV.has_key?('SUB_USERNAME') && ENV.has_key?('SUB_PASSWORD')
    config.registration.username = ENV['SUB_USERNAME']
    config.registration.password = ENV['SUB_PASSWORD']
  end

  # vagrant-service-manager plugin will configure openshift service by default for CDK
  config.servicemanager.services = "docker"


  config.vm.provision "shell", inline: <<-SHELL
       systemctl enable openshift
       systemctl start openshift
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    echo
    echo "Successfully started and provisioned VM with #{VM_CPU} cores and #{VM_MEMORY} MB of memory."
    echo "To modify the number of cores and/or available memory set the environment variables"
    echo "VM_CPU respectively VM_MEMORY."
    echo
    echo "You can now access the OpenShift console on: https://#{PUBLIC_ADDRESS}:8443/console"
    echo
    echo "To use OpenShift CLI, run:"
    echo "$ vagrant ssh"
    echo "$ oc login #{PUBLIC_ADDRESS}:8443"
    echo
    echo "Configured users are (<username>/<password>):"
    echo "openshift-dev/devel"
    echo "admin/admin"
    echo
    echo "If you have the oc client library on your host, you can also login from your host."
    echo
  SHELL
end
```

**Comment by LalatenduMohanty** [comment]
Closing the issue as the issue is being fixed in https://github.com/projectatomic/vagrant-service-manager/pull/167 and  in issue https://github.com/projectatomic/vagrant-service-manager/issues/166

**Comment by hferentschik** [comment]
> Now we found systemctl enable openshift writes to stderr about linking the unit file but this is not an error, and the exit code is 0. 

Makes sense, I was always wondering why this line was appearing in the 'vagrant up' we already had, especially since the startup otherwise continued. I hope this message will be gone in the end, since it was misleading anyways.

BTW, any idea why _systemctl_ would write to stderr? That seems odd.

> VSM sees something on stderr, assumes an error has occurred and exits with error code 126. (currently VSM only checking stderr, if there is something then we are blindly exitiing)

Got you. I wish I had created an issue about the linking message during 'vagrant up' before, then we might have caught this earlier. Just shows that one should not ignore these things.

> We already have a patch for it now

Nice, so we just need a vagrant-service-manager 1.0.1?
